### ISSUE TITLE
Hey here is a bug block me!

### ISSUE THREAD

**Issue by ipoly** [ScreamZ/anti-captcha#13]
https://github.com/ScreamZ/anti-captcha/blob/234a7fe08646e45d8cc47469fdd7bca2fa0e215a/src/AntiCaptcha.ts#L94-L100

**Comment by ScreamZ** [comment]
Damn, it should be related to the last merge, can you make a PR to fix ? I've tested since a long time

**Comment by ScreamZ** [comment]
Fixed in #14, `v2.0.1`
