### ISSUE TITLE
AntiCaptchaError isn't exported

### ISSUE THREAD

**Issue by yovanoc** [ScreamZ/anti-captcha#15]
You put in the readme that we can import AntiCaptchaError but is not exported. thanks

**Comment by ScreamZ** [comment]
Dammit, I merged too quick a pull request from someone, Ima fix this quickly, but I need your feedback guys as i cannot test it live for now, i ping u when it's ready

**Comment by yovanoc** [comment]
No worry. And I see you mixed these two things in the readme too:

`websiteKey: "http://www.some-site.com",
          websiteURL: "7Lfh6tkSBBBBBBGN68s8fAVds_Fl-HP0xQGNq1DK",`

**Comment by ScreamZ** [comment]
Fixed, can you check `2.0.2` ?

**Comment by yovanoc** [comment]
yes it's working.

I see this in doc too:

`if (await !AntiCaptchaAPI.isBalanceGreaterThan(10)) {`

should be

`if (!(await AntiCaptchaAPI.isBalanceGreaterThan(10))) {`

**Comment by ScreamZ** [comment]
I fix that too thanks mate!

**Comment by yovanoc** [comment]
Ahah no worries. Thanks for this lib!
