### ISSUE TITLE
createTask returning false

### ISSUE THREAD

**Issue by holtc** [ScreamZ/anti-captcha#16]
I am probably doing something wrong here, but why would `createTask` return `false`?  My example js code is below following the example in the README

```
const taskId = await AntiCaptchaAPI.createTask<IRecaptchaV3TaskProxyless>({
  type: TaskTypes.RECAPTCHA_PROXYLESS,
  websiteKey: sitekey,
  websiteURL: url
})
```

Not sure the generic type is allowed in js? When I try without, I get errors like: `Error: Some of the required values for successive user emulation are missing. Missing property 'pageAction'` or `Error: Some of the required values for successive user emulation are missing. Missing property 'minScore'` or `Error: Some of the required values for successive user emulation are missing. Missing property 'pageAction'`

```
const taskId = await AntiCaptchaAPI.createTask({
  type: TaskTypes.RECAPTCHA_PROXYLESS,
  websiteKey: sitekey,
  websiteURL: url
})
```

Any guidance? I am updating from `1.0.6` to `2.0.3`.  Are these new parameters required?

**Comment by ScreamZ** [comment]
Generic types are not supported in JS, I merged maybe a bit quickly the pull request from one guy 😅 Haven't tested much yet

@yovanoc @ipoly @ejhayes Maybe could you helps guys ?

**Comment by ejhayes** [comment]
Hi @holtc -- note that the use of generics are only if you're using this library with typescript. As for the error you're getting, there are a couple additional required parameters for this task type:
https://anticaptcha.atlassian.net/wiki/spaces/API/pages/623869953/RecaptchaV3TaskProxyless+Google+Recaptcha+v.3

I would imagine specifying `pageAction` and `minScore` would probably fix your issue. If you take a look at the interfaces for `IRecaptchaV3TaskProxyless ` you'll see that these are required params:
https://github.com/ScreamZ/anti-captcha/blob/master/src/interfaces.ts#L97

**Comment by holtc** [comment]
Gotcha, this changed from `1.0.6` where only the `websiteKey` and `url` were needed as params. Will check to see what those were defaulting to in past versions now that they are required

**Comment by ScreamZ** [comment]
Thanks for answer :)

**Comment by ejhayes** [comment]
@holtc  for recaptcha you can also use the `INoCaptchaTaskProxyless`. The only required parameters for that are websiteURL and websiteKey:

https://anticaptcha.atlassian.net/wiki/spaces/API/pages/9666606/NoCaptchaTaskProxyless+Google+Recaptcha+puzzle+solving+without+proxies

https://github.com/ScreamZ/anti-captcha/blob/master/src/interfaces.ts#L64
