### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by leumasme** [ScreamZ/anti-captcha#17]
Anticaptcha depends on apisauce "^1.1.1" (currently matches 1.1.2, latest is 2.1.1)
apisauce "1.1.2" then depends on axios "^0.19.0" (currently matches 0.19.2, latest is 0.21.1)
axios versions pre-0.21.1 have a high-severity vulnurability, see [https://www.npmjs.com/advisories/1594](NPM advisories)
This causes a warning message whenever installing anticaptcha via NPM:
`4 vulnerabilities (1 moderate, 3 high)`
Please update APIsauce to 2.1.1
As this is a major release update, i don't feel confident in doing this myself and testing if anything broke.

**Comment by aren55555** [comment]
Is there any plan to update this? Are contributions welcomed?

**Comment by ScreamZ** [comment]
Released under `v2.1.1`
