### ISSUE TITLE
module "anticaptcha" has no exported member 'Error Types'

### ISSUE THREAD

**Issue by AnthonyLzq** [ScreamZ/anti-captcha#27]
I was following the example in the docs:

```js
import {
  AntiCaptcha,
  AntiCaptchaError,
  ErrorTypes,
  INoCaptchaTaskProxyless,
  INoCaptchaTaskProxylessResult,
  QueueTypes,
  TaskTypes
} from "anticaptcha"
```

But then that error show up.

**Comment by ScreamZ** [comment]
Which error ?

**Comment by AnthonyLzq** [comment]
`Module '"anticaptcha"' has no exported member 'ErrorTypes'.`

![image](https://user-images.githubusercontent.com/43073718/160453892-f2799da0-b07f-422b-b879-fba910b81a1b.png)

**Comment by ShufflePerson** [comment]
late reply but docs aer outdated, the new type name is ErrorCodes,

**Comment by ScreamZ** [comment]
@ShufflePerson Fixed readme
