### ISSUE TITLE
Support multiple task types

### ISSUE THREAD

**Issue by LoveMHz** [ScreamZ/anti-captcha#3]
I'm interested in using this library but need to use ImageToTextTask. I would love to implement this myself and submit a pull request. Do you have any suggestions on expanding the current code for this functionality?

**Comment by ScreamZ** [comment]
Hi,

The simplest way would be:

1. Update The TaskType Enumeration accordingly.
2. Create an interface that describe requested params for the job type.
3. Create an union type which is whether new job type or previous.
4. Use it as function definition.

**Comment by ScreamZ** [comment]
@LoveMHz Any news about that ?

**Comment by botzill** [comment]
Hi. Do you have updates for other tasks types?

**Comment by ScreamZ** [comment]
@botzill Nope, didn't used since a while, but feel free to make a pull request about it, the code is pretty simple to understand. :)

**Comment by ScreamZ** [comment]
@LoveMHz It's been released in v2
