### ISSUE TITLE
it works well some sites, does not some sites.

### ISSUE THREAD

**Issue by kztmk** [ScreamZ/anti-captcha#4]
Thank you for grate wrapper.

`
const AntiCaptchaAPI = new AntiCaptcha(antiCaptchaKey);
`
When I make an instance of AntiCaptcha, in some sites come no error, but some sites come error "TypeError: _anticaptcha2.default is not a constructor".

How can I avoid this error?

**Comment by ScreamZ** [comment]
Can you give me intel about the import statement you are using ? Which ES version do you target ? Are you using a transpiler (babel ? typscript ?) ? webpack ?

**Comment by kztmk** [comment]
Thank you for quick response and sorry for late reply.

my import statement is folloing.

`import AntiCaptcha from "anticaptcha";`

and my target is ES2015.

Also I use

babel-core 6.26.3
webpack 4.16.3

Please tell me if you need more information.

**Comment by ScreamZ** [comment]
This is meant to be used server side in will, if you're using it client side you must be sure that the browser is supporting `ES6 syntax`. Do you still have the issue @kztmk ?

**Comment by kztmk** [comment]
Thank you for replay.

I still have the same error.

My environment is

electron 2.0.6
babel-core 6.26.3
webpack 4.15.3

call to puppeteer 1.10.0

when puppeteer access to site for creating contents, site require the recaptcha. It work on some sites, it does not some sites.

If you need some more information, please let me know. 

Thanks so much.

**Comment by ScreamZ** [comment]
The thing I don't get is why sometimes the constructor is recognised and sometimes not. If you tell me that the captcha verification remain invalid I could have understand but there…

The import syntax should be the following, if you're using babel and webpack loader I guess you can use the ESM syntax. Did you try to `console.log` the import ?

```js
// On ESM
import { AntiCaptcha } from "anticaptcha";

// Using commonjs (nodejs based)
const AntiCaptcha = require('anticaptcha').AntiCaptcha
```
